pull_request_rules:
  - name: automatic merge when CI passes and 1 reviews
    conditions:
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "#review-threads-unresolved=0"
      - base=main
      - check-success=Lint
      - check-success=Build & Test (ubuntu-latest)
      - check-success=Build & Test (windows-latest)
      - check-success=Build & Test (macOS-latest)
      - check-success=Publish Check
      - label!=block-automerge
    actions:
      merge:
        method: squash
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
